### Get all users
GET http://127.0.0.1:3000/api/v1/users
Accept: application/json

### Add a new user
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
  "username": "joha123",
  "name": "",
  "email": "john@test.com",
  "role": "student / failed comedian",
  "password": "123"
}


### Get user by ID
GET http://127.0.0.1:3000/api/v1/users/53
Accept: application/json

### Update user info
PUT http://127.0.0.1:3000/api/v1/users/53
Content-Type: application/json

{
  "username": "Don Corleone"
}

### Delete user
DELETE http://127.0.0.1:3000/api/v1/users/51
